FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copiamos el jar compilado
COPY target/*.jar app.jar

# Copiamos el wallet dentro del contenedor
COPY src/main/resources/Wallet_BDFS3 /app/wallet

EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
